import { Audio } from 'expo-av';
import * as FileSystem from 'expo-file-system/legacy'; // Ensure using legacy if that's your setup
import { Stack, useRouter } from 'expo-router';
import React, { useEffect, useRef, useState } from 'react';
import { Alert, StyleSheet, View, useColorScheme } from 'react-native';

import AudioNotesHeader from '@/components/AudioNotesHeader';
import ProcessingView from '@/components/ProcessingView';
import RecordView from '@/components/RecordView';
import ResultView from '@/components/ResultView';
import SaveModal from '@/components/SaveModal';
import { Colors } from '@/constants/theme';

// 👇 1. IMPORT YOUR CONTEXT
import { useFileSystem } from '@/contexts/FileSystemContext';

const formatTime = (seconds: number) => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins < 10 ? '0' : ''}${mins}:${secs < 10 ? '0' : ''}${secs}`;
};

export default function RecordScreen() {
  const colorScheme = useColorScheme() ?? 'light';
  const themeColors = Colors[colorScheme];
  const router = useRouter();

  // 👇 2. GET THE CREATE FUNCTION
  const { createFile } = useFileSystem();

  const [stage, setStage] = useState<'record' | 'processing' | 'done'>('record');
  const [recording, setRecording] = useState<Audio.Recording | null>(null);
  const [permissionResponse, requestPermission] = Audio.usePermissions();
  const [timer, setTimer] = useState(0);
  const [audioUri, setAudioUri] = useState<string | null>(null);
  const [transcript, setTranscript] = useState("");
  const [isSaveModalVisible, setIsSaveModalVisible] = useState(false);

  const timerInterval = useRef<any>(null);

  useEffect(() => {
    (async () => {
      if (!permissionResponse) await requestPermission();
    })();
    return () => {
      if (timerInterval.current) clearInterval(timerInterval.current);
      if (recording) recording.stopAndUnloadAsync();
    };
  }, []);

  const startRecording = async () => {
    try {
      if (permissionResponse?.status !== 'granted') await requestPermission();

      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
      });

      const { recording: newRecording } = await Audio.Recording.createAsync(
        Audio.RecordingOptionsPresets.HIGH_QUALITY
      );
      
      setRecording(newRecording);
      setTimer(0);
      timerInterval.current = setInterval(() => setTimer((prev) => prev + 1), 1000);
    } catch (err) {
      Alert.alert('Error', 'Could not start recording.');
    }
  };

  const stopRecording = async () => {
    if (!recording) return;
    if (timerInterval.current) clearInterval(timerInterval.current);
    setRecording(null); 
    await recording.stopAndUnloadAsync();
    const uri = recording.getURI();
    setAudioUri(uri); 
  };

  const handleToggleRecord = async () => {
    if (recording) {
      await stopRecording();
    } else {
      await startRecording();
    }
  };

  const handleTranscribe = async () => {
    if (recording) await stopRecording();
    setStage('processing');
    setTimeout(() => {
      setTranscript(""); 
      setStage('done');
    }, 2000);
  };

  const handleRestart = async () => {
    if (recording) await recording.stopAndUnloadAsync();
    setRecording(null);
    setAudioUri(null);
    setTimer(0);
    setTranscript("");
    if (timerInterval.current) clearInterval(timerInterval.current);
    setStage('record');
  };

  // 👇 3. REPLACED SAVE LOGIC
  const handleFinalSave = async (fileName: string) => {
    if (!audioUri) {
      Alert.alert("Error", "No audio file found.");
      return;
    }

    try {
      const finalName = fileName.trim() || `Recording ${new Date().toLocaleTimeString()}`;

      // A. Create Metadata in Context (Get a unique ID)
      // Passing 'null' as folderId puts it in Root.
      const newId = await createFile(finalName, null, "Voice Note");

      // B. Determine Paths
      const FS = FileSystem as any;
      const rootDir = FS.documentDirectory || FS.cacheDirectory;
      const recordingsFolder = rootDir + 'recordings/';
      
      // We rename the file to match the ID generated by the context
      const destinationUri = recordingsFolder + newId + '.m4a';

      // C. Ensure 'recordings' folder exists (Crucial step!)
      const dirInfo = await FS.getInfoAsync(recordingsFolder);
      if (!dirInfo.exists) {
        await FS.makeDirectoryAsync(recordingsFolder, { intermediates: true });
      }

      // D. Move the temp file to the permanent location
      await FileSystem.moveAsync({ 
        from: audioUri, 
        to: destinationUri 
      });

      // E. Cleanup & Navigate
      setIsSaveModalVisible(false);
      Alert.alert("Success", "Recording saved!", [
        { text: "OK", onPress: () => router.replace('/(tabs)') } // Go back to Home
      ]);

    } catch (error) {
      console.error(error);
      Alert.alert("Error", "Failed to save file.");
    }
  };

  return (
    <View style={[styles.container, { backgroundColor: themeColors.background }]}>
      <Stack.Screen options={{ headerShown: false }} />
      <AudioNotesHeader hideSettings={true} />

      <View style={styles.contentWrapper}>
        {stage === 'record' && (
          <RecordView 
            isRecording={!!recording}
            hasRecording={!!audioUri} 
            recordingDuration={formatTime(timer)}
            onToggleRecord={handleToggleRecord}
            onRestart={handleRestart}
            onCancel={() => router.back()}
            onTranscribe={handleTranscribe}
            onSave={() => setIsSaveModalVisible(true)} 
          />
        )}

        {stage === 'processing' && (
          <ProcessingView onRestart={handleRestart} onCancel={() => router.back()} />
        )}

        {stage === 'done' && (
          <ResultView 
            transcript={transcript}
            onRestart={handleRestart}
            onCancel={() => router.back()}
            onSave={() => setIsSaveModalVisible(true)}
          />
        )}
      </View>

      <SaveModal 
        isVisible={isSaveModalVisible}
        onClose={() => setIsSaveModalVisible(false)}
        onSave={handleFinalSave}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  contentWrapper: { flex: 1 },
});